### ISSUE TITLE
cant able to find some files for modification

### ISSUE THREAD

**Issue by Prajakta2011** [education/codespaces-teaching-template-js#25]
i am trying to make portfolio using template but i cant able to find some file like imageALTtext, about.jsx, portfolio.jsx  where are they? in which folder?

**Comment by saragibby** [comment]
Hi @Prajakta2011! Apologies for the delay, it sounds like you are looking for the [JavaScript Portfolio Site with GitHub Codespaces](https://github.com/education/codespaces-project-template-js) project. There you will find the files for the portfolio site where the imageALTtext fields is located. Enjoy the project!
